// frontend/src/lib/dietDb.js

export const CUISINES = ['All', 'Indian', 'Asian', 'Western', 'Mediterranean', 'Mexican', 'Supplements']

export const MEAL_CATEGORIES = [
  { id: 'breakfast', name: 'Breakfast', emoji: '🌅' },
  { id: 'lunch', name: 'Lunch', emoji: '☀️' },
  { id: 'dinner', name: 'Dinner', emoji: '🌙' },
  { id: 'snacks', name: 'Snacks & Fuel', emoji: '🍎' },
]

export const COMMON_FOODS = [
  // --- INDIAN CUISINE ---
  {
    id: 'ind_paneer',
    name: 'Paneer (Raw)',
    cuisine: 'Indian',
    baseQty: 100,
    unit: 'g',
    calories: 265,
    protein: 18.3,
    carbs: 3.4,
    fat: 20.8,
    fiber: 0,
    sodium: 18,
    calcium: 480,
  },
  {
    id: 'ind_roti',
    name: 'Whole Wheat Roti / Chapati',
    cuisine: 'Indian',
    baseQty: 1,
    unit: 'piece (35g)',
    calories: 104,
    protein: 3.2,
    carbs: 21.0,
    fat: 0.8,
    fiber: 2.8,
    sodium: 110,
    potassium: 90,
  },
  {
    id: 'ind_dal_tadka',
    name: 'Yellow Dal (Cooked)',
    cuisine: 'Indian',
    baseQty: 100,
    unit: 'g',
    calories: 116,
    protein: 7.2,
    carbs: 17.5,
    fat: 2.3,
    fiber: 4.2,
    sodium: 230,
    iron: 1.8,
  },
  {
    id: 'ind_chana_masala',
    name: 'Chickpeas / Chana Masala',
    cuisine: 'Indian',
    baseQty: 100,
    unit: 'g',
    calories: 138,
    protein: 6.8,
    carbs: 22.1,
    fat: 2.8,
    fiber: 5.5,
    sodium: 280,
    iron: 2.1,
  },
  {
    id: 'ind_dosa',
    name: 'Plain Dosa',
    cuisine: 'Indian',
    baseQty: 1,
    unit: 'medium (80g)',
    calories: 168,
    protein: 3.9,
    carbs: 29.0,
    fat: 4.1,
    fiber: 1.4,
    sodium: 190,
  },
  {
    id: 'ind_idli',
    name: 'Steamed Idli',
    cuisine: 'Indian',
    baseQty: 1,
    unit: 'piece (40g)',
    calories: 58,
    protein: 1.8,
    carbs: 12.0,
    fat: 0.2,
    fiber: 0.8,
    sodium: 65,
  },
  {
    id: 'ind_chicken_curry',
    name: 'Home-style Chicken Curry',
    cuisine: 'Indian',
    baseQty: 100,
    unit: 'g',
    calories: 145,
    protein: 16.5,
    carbs: 3.8,
    fat: 7.2,
    fiber: 1.1,
    sodium: 320,
  },
  {
    id: 'ind_curd',
    name: 'Dahi / Curd (Plain)',
    cuisine: 'Indian',
    baseQty: 100,
    unit: 'g',
    calories: 61,
    protein: 3.5,
    carbs: 4.7,
    fat: 3.3,
    fiber: 0,
    sodium: 46,
    calcium: 120,
  },

  // --- ASIAN / EAST ASIAN ---
  {
    id: 'as_white_rice',
    name: 'White Jasmine / Basmati Rice (Cooked)',
    cuisine: 'Asian',
    baseQty: 100,
    unit: 'g',
    calories: 130,
    protein: 2.7,
    carbs: 28.2,
    fat: 0.3,
    fiber: 0.4,
    sodium: 1,
    potassium: 35,
  },
  {
    id: 'as_tofu_firm',
    name: 'Firm Tofu',
    cuisine: 'Asian',
    baseQty: 100,
    unit: 'g',
    calories: 83,
    protein: 10.0,
    carbs: 1.9,
    fat: 5.3,
    fiber: 1.0,
    sodium: 8,
    calcium: 205,
  },
  {
    id: 'as_edamame',
    name: 'Edamame (Steamed)',
    cuisine: 'Asian',
    baseQty: 100,
    unit: 'g',
    calories: 121,
    protein: 11.9,
    carbs: 8.9,
    fat: 5.2,
    fiber: 5.2,
    sodium: 6,
    iron: 2.3,
  },
  {
    id: 'as_teriyaki_chicken',
    name: 'Teriyaki Chicken Thigh',
    cuisine: 'Asian',
    baseQty: 100,
    unit: 'g',
    calories: 178,
    protein: 21.0,
    carbs: 6.2,
    fat: 7.5,
    fiber: 0.2,
    sodium: 480,
  },
  {
    id: 'as_ramen_noodles',
    name: 'Ramen / Soba Noodles (Cooked)',
    cuisine: 'Asian',
    baseQty: 100,
    unit: 'g',
    calories: 142,
    protein: 4.9,
    carbs: 27.5,
    fat: 1.2,
    fiber: 1.3,
    sodium: 180,
  },

  // --- WESTERN ---
  {
    id: 'wes_chicken_breast',
    name: 'Chicken Breast (Skinless, Grilled)',
    cuisine: 'Western',
    baseQty: 100,
    unit: 'g',
    calories: 165,
    protein: 31.0,
    carbs: 0.0,
    fat: 3.6,
    fiber: 0,
    sodium: 74,
    potassium: 256,
  },
  {
    id: 'wes_egg_whole',
    name: 'Large Egg (Whole, Boiled)',
    cuisine: 'Western',
    baseQty: 1,
    unit: 'large (50g)',
    calories: 72,
    protein: 6.3,
    carbs: 0.4,
    fat: 4.8,
    fiber: 0,
    sodium: 71,
    calcium: 28,
  },
  {
    id: 'wes_egg_whites',
    name: 'Liquid Egg Whites',
    cuisine: 'Western',
    baseQty: 100,
    unit: 'g',
    calories: 52,
    protein: 11.0,
    carbs: 0.7,
    fat: 0.2,
    fiber: 0,
    sodium: 166,
    potassium: 163,
  },
  {
    id: 'wes_oats',
    name: 'Rolled Oats (Dry)',
    cuisine: 'Western',
    baseQty: 50,
    unit: 'g',
    calories: 189,
    protein: 6.5,
    carbs: 34.0,
    fat: 3.2,
    fiber: 5.1,
    sodium: 2,
    iron: 1.9,
  },
  {
    id: 'wes_greek_yogurt',
    name: 'Greek Yogurt (0% Fat)',
    cuisine: 'Western',
    baseQty: 100,
    unit: 'g',
    calories: 59,
    protein: 10.2,
    carbs: 3.6,
    fat: 0.4,
    fiber: 0,
    sodium: 36,
    calcium: 110,
  },
  {
    id: 'wes_peanut_butter',
    name: 'Natural Peanut Butter',
    cuisine: 'Western',
    baseQty: 32,
    unit: 'g (2 tbsp)',
    calories: 190,
    protein: 8.0,
    carbs: 6.0,
    fat: 16.0,
    fiber: 2.0,
    sodium: 5,
    potassium: 210,
  },
  {
    id: 'wes_banana',
    name: 'Banana (Fresh)',
    cuisine: 'Western',
    baseQty: 1,
    unit: 'medium (118g)',
    calories: 105,
    protein: 1.3,
    carbs: 27.0,
    fat: 0.3,
    fiber: 3.1,
    sodium: 1,
    potassium: 422,
  },

  // --- MEDITERRANEAN ---
  {
    id: 'med_salmon',
    name: 'Atlantic Salmon Fillet (Grilled)',
    cuisine: 'Mediterranean',
    baseQty: 100,
    unit: 'g',
    calories: 206,
    protein: 22.1,
    carbs: 0.0,
    fat: 12.3,
    fiber: 0,
    sodium: 61,
    potassium: 384,
  },
  {
    id: 'med_olive_oil',
    name: 'Extra Virgin Olive Oil',
    cuisine: 'Mediterranean',
    baseQty: 14,
    unit: 'ml (1 tbsp)',
    calories: 119,
    protein: 0.0,
    carbs: 0.0,
    fat: 13.5,
    fiber: 0,
    sodium: 0,
  },
  {
    id: 'med_hummus',
    name: 'Hummus (Traditional)',
    cuisine: 'Mediterranean',
    baseQty: 50,
    unit: 'g',
    calories: 83,
    protein: 2.5,
    carbs: 7.2,
    fat: 4.8,
    fiber: 2.0,
    sodium: 190,
  },

  // --- MEXICAN ---
  {
    id: 'mex_black_beans',
    name: 'Black Beans (Boiled)',
    cuisine: 'Mexican',
    baseQty: 100,
    unit: 'g',
    calories: 132,
    protein: 8.9,
    carbs: 23.7,
    fat: 0.5,
    fiber: 8.7,
    sodium: 2,
    iron: 2.1,
  },
  {
    id: 'mex_avocado',
    name: 'Avocado (Raw)',
    cuisine: 'Mexican',
    baseQty: 100,
    unit: 'g',
    calories: 160,
    protein: 2.0,
    carbs: 8.5,
    fat: 14.7,
    fiber: 6.7,
    sodium: 7,
    potassium: 485,
  },

  // --- SUPPLEMENTS ---
  {
    id: 'sup_whey_isolate',
    name: 'Whey Isolate Powder',
    cuisine: 'Supplements',
    baseQty: 1,
    unit: 'scoop (30g)',
    calories: 115,
    protein: 27.0,
    carbs: 1.0,
    fat: 0.5,
    fiber: 0,
    sodium: 95,
    calcium: 135,
  },
  {
    id: 'sup_casein',
    name: 'Casein Protein Powder',
    cuisine: 'Supplements',
    baseQty: 1,
    unit: 'scoop (32g)',
    calories: 120,
    protein: 24.0,
    carbs: 2.0,
    fat: 1.0,
    fiber: 0,
    sodium: 140,
    calcium: 500,
  },
]

/**
 * Calculates scaled nutrients based on user quantity
 */
export function scaleNutrients(food, targetQty) {
  const qty = Number(targetQty) || 0
  const factor = qty / (food.baseQty || 1)

  return {
    calories: Math.round(food.calories * factor),
    protein: Number((food.protein * factor).toFixed(1)),
    carbs: Number((food.carbs * factor).toFixed(1)),
    fat: Number((food.fat * factor).toFixed(1)),
    fiber: Number(((food.fiber || 0) * factor).toFixed(1)),
    sodium: Math.round((food.sodium || 0) * factor),
    potassium: Math.round((food.potassium || 0) * factor),
    calcium: Math.round((food.calcium || 0) * factor),
    iron: Number(((food.iron || 0) * factor).toFixed(1)),
  }
}

export function computeDailyTotals(meals = []) {
  return meals.reduce(
    (acc, item) => ({
      calories: acc.calories + (Number(item.calories) || 0),
      protein: acc.protein + (Number(item.protein) || 0),
      carbs: acc.carbs + (Number(item.carbs) || 0),
      fat: acc.fat + (Number(item.fat) || 0),
      fiber: acc.fiber + (Number(item.fiber) || 0),
      sodium: acc.sodium + (Number(item.sodium) || 0),
    }),
    { calories: 0, protein: 0, carbs: 0, fat: 0, fiber: 0, sodium: 0 }
  )
}